backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: src/assets/img
public_folder: src/assets/img

collections:
  - name: "Post"
    label: "Post"
    folder: "src/pages/posts"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../src/layouts/MarkdownPostLayout.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}"}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags",  widget: "list",  allow_add: false,  default: ["news"]}
      - { label: "Body", name: "body", widget: "markdown" }
      